---

freefeed_env: stable
freefeed_media_hostname: stable-media.freefeed.net
freefeed_server_version: stable
freefeed_s3_bucket: freefeed-storage-test
freefeed_s3_region: eu-west-1
freefeed_s3_media_base_url: http://stable-media-r2.freefeed.net
freefeed_storage_type: s3
freefeed_base_port: 4000
freefeed_jobs_enabled: false

imgproxy_port: 9998

auth_token_prefix: micropeppa_

postgres_host: 172.18.0.1
postgres_port: 5432
postgres_user: stagefeed
postgres_dbname: stagefeed
postgres_textsearch_config: public.freefeed_fts

new_relic_app_name: "FreeFeed stable"
public_sentry_dsn: 'https://c0d1b60991264cc4b56a1398db012900@sentry.io/79081'
monitor_prefix: candy
freefeed_external_auth_providers_enabled: true
redis_host: "redis-{{ freefeed_env }}"
freefeed_server_instances: 1

ansible_python_interpreter: /usr/bin/python3

invite_registrations_form_iframe_src: "https://docs.google.com/forms/d/e/1FAIpQLSdBzsUIHzR57Ylt2AfUfbIf9Bc03I8Oq2SdQmYqp0s-OsWmnw/viewform?embedded=true"

use_imgproxy: true

privacy_control_groups:
  public:
    label: "Makes post public"
    privacy: "public"
  protected:
    label: "Makes post protected"
    privacy: "protected"
