---

pepyatka_hostname: candy.freefeed.net
pepyatka_media_hostname: stable-media.freefeed.net
pepyatka_server_branch: stable
pepyatka_ansible_branch: development
pepyatka_s3_bucket: freefeed-storage-test
pepyatka_deploy_inventory: stable

react_client_branch: stable
react_client_hostname: candy.freefeed.net

vanilla_enabled: false

nginx_load_balancer_source: '172.31.0.0/16'

auth_token_prefix: micropeppa_

public_sentry_dsn: 'https://c0d1b60991264cc4b56a1398db012900@sentry.io/79081'
freefeed_external_auth_providers_enabled: true
new_relic_app_name: "FreeFeed Stable"
monitor_prefix: candy