---

- name: Install nginx
  become: yes
  package:
    name: nginx
    state: present

- name: Render ssl.conf
  become: yes
  template:
    src: ssl.conf.j2
    dest: /etc/nginx/ssl.conf
  register: ssl_conf
  tags:
    - config

- name: Render nginx.conf
  become: yes
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  register: nginx_conf
  tags:
    - config

- name: Ensure /etc/nginx/conf.d
  become: yes
  file:
    path: /etc/nginx/conf.d
    state: directory
  tags:
    - config

- name: Render /etc/nginx/conf.d/{{ freefeed_hostname }}.conf
  become: yes
  template:
    src: site.conf.j2
    dest: "/etc/nginx/conf.d/{{ freefeed_hostname }}.conf"
  register: site_conf
  tags:
    - config

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  when: nginx_conf.changed or ssl_conf.changed or site_conf.changed
