---

- name: Check if pepyatka-lite repo already exists
  stat: path=/var/www/pepyatka-lite/.git
  register: pepyatka_lite_dir
  tags:
    - pepyatka
    - nginx

- name: Initial deploy of pepyatka-lite
  git:
    repo: "{{ pepyatka_lite_repo }}"
    dest: /var/www/pepyatka-lite
    version: "{{ pepyatka_lite_branch }}"
  when: not pepyatka_lite_dir.stat.exists
  register: pepyatka_lite_init
  tags:
    - pepyatka
    - nginx

- name: Get pepyatka-lite local version
  command: chdir=/var/www/pepyatka-lite git rev-parse HEAD
  register: pepyatka_lite_local_version
  tags:
    - pepyatka
    - nginx

- name: Fetch pepyatka-lite remote
  command: chdir=/var/www/pepyatka-lite git fetch origin
  tags:
    - pepyatka
    - nginx

- name: Get pepyatka-lite version on remote
  command: chdir=/var/www/pepyatka-lite git rev-parse origin/{{ pepyatka_lite_branch }}
  register: pepyatka_lite_remote_version
  tags:
    - pepyatka
    - nginx

- name: Update pepyatka-lite
  git:
    repo: "{{ pepyatka_lite_repo }}"
    update: yes
    dest: /var/www/pepyatka-lite
    version: "{{ pepyatka_lite_branch }}"
    force: yes
  register: pepyatka_lite
  when: pepyatka_lite_local_version.stdout != pepyatka_lite_remote_version.stdout
  tags:
    - pepyatka
    - nginx

- name: Save changelog in a file
  shell: echo "{{ pepyatka_lite_local_version.stdout }}...{{ pepyatka_lite_remote_version.stdout }}" > /tmp/pepyatka-lite-changelog
  when: pepyatka_lite_local_version.stdout != pepyatka_lite_remote_version.stdout
  tags: pepyatka

- name: Fetch pepyatka-lite changelog
  fetch:
    src=/tmp/pepyatka-lite-changelog
    dest=pepyatka-lite-changelog/{{ inventory_hostname }}
    flat=yes
  when: pepyatka_lite_local_version.stdout != pepyatka_lite_remote_version.stdout
  tags: pepyatka

- name: Deploy pepyatka-lite config
  template: src=pepyatka-lite-config.json.j2 dest=/var/www/pepyatka-lite/config.json
  tags:
    - pepyatka
    - nginx

- name: Install webpack globally
  npm: name=webpack state=latest global=yes
  tags:
    - pepyatka
    - nginx

- name: Kill local node_modules
  file: path=/var/www/pepyatka-lite/node_modules state=absent
  when: pepyatka-lite | changed
  tags:
    - pepyatka
    - nginx

- name: Install pepyatka-lite dependencies
  npm: path=/var/www/pepyatka-lite state=latest
  tags:
    - pepyatka
    - nginx

- name: Build the bundle 
  command: chdir=/var/www/pepyatka-lite webpack --config config.js
  tags:
    - pepyatka
    - nginx

- name: Deploy md5 script
  copy: src=write_hash.sh dest=/var/www/pepyatka-lite/ mode=0755
  tags:
    - pepyatka
    - nginx

- name: Append md5 hashes to file urls
  command: chdir=/var/www/pepyatka-lite ./write_hash.sh
  tags:
    - pepyatka
    - nginx

- name: Update ga account
  replace:
    dest: /var/www/pepyatka-lite/config.json
    regexp: "UA-0-1"
    replace: "{{ pepyatka_ga_account }}"
  tags:
    - pepyatka
    - nginx

- name: Sync standard images from pepyatka-html
  command: rsync -a --delete /var/www/pepyatka-html/public/img /var/www/pepyatka-lite
  tags:
    - pepyatka
    - nginx

- name: Fix pepyatka-lite permissions
  file:
    path: /var/www/pepyatka-lite
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    state: directory
    recurse: yes
  tags:
    - pepyatka
    - nginx
