---

- name: Ensure git is installed
  apt: name=git state=present

- name: Deploy react-client
  git:
    repo: "{{ react_client_repo }}"
    update: yes
    dest: "{{ react_client_dir }}"
    version: "{{ react_client_branch }}"
    force: yes
  register: react_client

- name: Save changelog in a file
  shell: echo "{{ react_client.before }}...{{ react_client.after }}" > /tmp/react-client-changelog
  when: react_client.before != react_client.after

- name: Fetch react-client changelog
  fetch:
    src=/tmp/react-client-changelog
    dest="react-client-changelog/{{ inventory_hostname }}"
    flat=yes
  when: react_client.before != react_client.after

- name: Kill local node_modules
  file: path="{{ react_client_dir }}/node_modules" state=absent
  when: react_client.before != react_client.after

- name: Install fresh YARN
  command: npm install -g yarn

- name: Install dependencies
  command: yarn install
  args:
    chdir: "{{ react_client_dir }}"

- name: Build assets
  command: make prod out_dir="{{ react_client_dir }}/public"
  args:
    chdir: "{{ react_client_dir }}"

- name: Ensure "{{ react_client_dir }}/public/js"
  file: path="{{ react_client_dir }}/public/js" state=directory

- name: Ensure "{{ react_client_dir }}/config"
  file: path="{{ react_client_dir }}/config" state=directory

- name: Fetch local.json
  shell: "aws s3 cp s3://freefeed-config/freefeed-react-client/{{ react_client_branch }}/local.json ./"
  args:
    chdir: "{{ react_client_dir }}/config"

- name: Fix permissions
  file:
    path: "{{ react_client_dir }}"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    state: directory
    recurse: yes

