---
language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible

script:
  - echo $ANSIBLE_VAULT_PASSWORD > ~/.pepyatka.vault
  - rm -rf plugins/callback/datadog.*
  - ansible-playbook -vv -i local aws/route53.yml
