---

www_user: www-data
www_group: www-data

pepyatka_frontend_scheme: http
pepyatka_server_host: localhost
pepyatka_server_instances:
  - 3000
pepyatka_files_dir: /var/pepyatka-files
pepyatka_s3_bucket: ""
pepyatka_ga_account: "UA-XXXXXX"

nginx_client_max_body_size: '10M'
nginx_use_proxy_protocol: False
nginx_proxy_protocol_real_ips: []

react_client_basic_auth_enabled: False
react_client_dir: /var/www/freefeed-react-client

vanilla_enabled: False
vanilla_dir: /var/www/pepyatka-lite
vanilla_hostname: localhost
vanilla_lead_domain: localhost
