---

- name: Ensure /etc/freefeed/{{ freefeed_site }}
  become: yes
  file:
    path: "/etc/freefeed/{{ freefeed_site }}"
    state: directory
  tags:
    - config

- name: Render /etc/freefeed/{{ freefeed_site }}/config.json
  become: yes
  template:
    src: config.json.j2
    dest: "/etc/freefeed/{{ freefeed_site }}/config.json"
  tags:
    - config

- set_fact:
    server_containers: []
  tags:
    - always

- set_fact:
    server_containers: "{{ server_containers + ['freefeed-server-'+freefeed_env+'-'+item] }}"
  with_sequence: count="{{ freefeed_server_instances }}"
  tags:
    - always

- name: Render /etc/freefeed/{{ freefeed_site }}/react-client.nginx.conf
  become: yes
  template: src="react-client.nginx.conf.j2" dest="/etc/freefeed/{{ freefeed_site }}/react-client.nginx.conf"
  tags:
    - config

- name: Create react-client-{{ freefeed_site }} container
  become: yes
  docker_container:
    name: "react-client-{{ freefeed_site }}"
    image: "{{ react_client_image }}"
    command: echo
    state: present
    pull: yes

- name: Start nginx-{{ freefeed_site }} container
  become: yes
  docker_container:
    name: "nginx-{{ freefeed_site }}"
    image: nginx:latest
    published_ports:
      - "{{ freefeed_client_port }}:80"
    volumes:
      - "/etc/freefeed/{{ freefeed_site }}/react-client.nginx.conf:/etc/nginx/nginx.conf:ro"
    networks:
      - name: freefeed
    purge_networks: yes
    networks_cli_compatible: no
    state: started
    restart_policy: on-failure

- name: Copy freefeed-react-client files
  become: yes
  shell: "docker cp react-client-{{ freefeed_site }}:/var/www/freefeed-react-client - | docker cp - nginx-{{ freefeed_site }}:/usr/share/nginx/"

- name: Copy config.json
  become: yes
  shell: "docker cp /etc/freefeed/{{ freefeed_site }}/config.json nginx-{{ freefeed_site }}:/usr/share/nginx/freefeed-react-client/"

