---

- name: Add apt key for the nodesource repository
  apt_key: url="https://deb.nodesource.com/gpgkey/nodesource.gpg.key" state=present
  tags:
    - nodejs

- name: Add the nodesource apt repository
  apt_repository: repo="deb https://deb.nodesource.com/node_4.x {{ ansible_lsb.codename }} main" state=present
  tags:
    - nodejs

- name: Install NodeJS packages
  apt: name=nodejs state=latest force=yes update_cache=yes
  tags:
    - nodejs

- name: Update alternatives
  alternatives: name=node path=/usr/bin/nodejs link=/usr/bin/node
  tags:
    - nodejs
