- name: Ensure user
  become: yes
  ansible.builtin.user:
    name: tg-client
    uid: 10001
    system: true
    home: "{{ freefeed_tg_client_home }}"
    create_home: true
    append: true
    groups:
      - docker

- name: Ensure data dir
  become: yes
  ansible.builtin.file:
    path: "{{ freefeed_tg_client_home }}/data"
    state: directory
    owner: tg-client
    group: tg-client
    mode: '0755'

- name: Render docker-compose.yml
  become: yes
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ freefeed_tg_client_home }}/docker-compose.yml"
    owner: tg-client
    group: tg-client

- name: Render systemd unit file
  become: yes
  template:
    src: "tg-client.service.j2"
    dest: "/etc/systemd/system/tg-client.service"
    mode: 0755

- name: Ensure tg-client.service is started
  become: yes
  ansible.builtin.systemd:
    state: started
    enabled: true
    daemon_reload: true
    name: tg-client.service
