---

# ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -vv -i ami aws/build-ami.yml

- hosts: aws
  gather_facts: no
  connection: local
  tasks:
    - name: Create security group for building AMIs
      local_action: ec2_group
      args:
        name: build-ami-sg
        description: Security group for building AMI (ssh access from any)
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        rules:
          - proto: tcp
            cidr_ip: 0.0.0.0/0
            from_port: 22
            to_port: 22

    - name: Launch an ami builder instance
      ec2:
        key_name: pepyatka-aws
        instance_type: t2.micro
        image: "{{ base_ami }}"
        wait: yes
        group: build-ami-sg
        count: 1
        region: "{{ region }}"
        vpc_subnet_id: "{{ ami_subnet_id }}"
      register: ec2

    - name: Print instance ip
      debug: msg="{{ ec2.instances[0].public_ip }}"

    - name: Print instance id
      debug: msg="{{ ec2.instances[0].id }}"

    - set_fact:
        instance_id: "{{ ec2.instances[0].id }}"
        instance_ip: "{{ ec2.instances[0].public_ip }}"

    - name: Add new instance to the host group
      add_host:
        hostname="{{ instance_ip }}"
        groups=target

    - name: Wait for SSH
      wait_for: host="{{ instance_ip }}" port=22 delay=90 timeout=320 state=started

    - pause: prompt="Wait a bit more" seconds=2

- include: ../playbooks/essentials.yml
- include: ../playbooks/admins.yml

- hosts: target
  become: yes
  roles:
    - pganalyze
    - nodejs
  tasks:
    - name: Stop and disable pganalyze-collector
      service: name=pganalyze-collector state=stopped enabled=false

    # TODO: figure out how to make it more secure
    #       put on KMS?
    - name: Copy vault password file
      copy: src=~/.freefeed-ansible.vault dest=/root/.freefeed-ansible.vault

- include: ../playbooks/check-deploy.yml

- hosts: ami_control_host
  connection: local
  gather_facts: false
  become: no
  tasks:
    - name: Build AMI
      ec2_ami:
        instance_id: "{{ instance_id }}"
        wait: yes
        name: "freefeed-api-server_{{ lookup('pipe', 'date -u +%Y%m%d_%H%M%S') }}"
        region: "{{ region }}"
        tags:
          Name: freefeed-api-server
      register: ami

    - debug: var=ami

    - name: Terminate ami builder instance
      ec2:
        state: absent
        instance_ids: "{{ instance_id }}"
        region: "{{ region }}"

