- name: Ensure "{{ freefeed_config_dir }}"
  become: yes
  file:
    path: "{{ freefeed_config_dir }}"
    state: directory

- name: Download mailchecker-list
  become: yes
  ansible.builtin.get_url:
    url: https://github.com/FGRibreau/mailchecker/raw/master/list.txt
    dest: "{{ freefeed_config_dir }}/mailchecker.txt"

- name: Render local-{{ freefeed_env }}.json
  become: yes
  template:
    src: local.json.j2
    dest: "{{ freefeed_config_dir }}/local-{{ freefeed_env }}.json"
  register: local_json
  tags:
    - local-json

- name: Start redis container
  become: yes
  docker_container:
    name: "redis-{{ freefeed_env }}"
    image: "redis:latest"
    state: started
    restart_policy: on-failure
    networks:
      - name: freefeed
    purge_networks: yes

- name: Run DB migrations
  become: yes
  docker_container:
    name: "freefeed-db-migration-{{ freefeed_env }}"
    image: "ghcr.io/freefeed/freefeed-server:{{ freefeed_server_version }}"
    command: "./node_modules/.bin/knex migrate:latest"
    detach: false
    volumes:
      - "{{ freefeed_config_dir }}/local-{{ freefeed_env }}.json:/server/config/local-{{ freefeed_env }}.json:ro"
      - "{{ freefeed_config_dir }}/banlist.txt:/etc/freefeed/banlist.txt:ro"
      - "{{ freefeed_config_dir }}/mailchecker.txt:/etc/freefeed/mailchecker.txt:ro"
    env:
      NODE_ENV: production
      NODE_CONFIG_ENV: "{{ freefeed_env }}"
    networks:
      - name: freefeed
    purge_networks: yes
    pull: yes
    state: started

- name: Ensure directory for logs
  become: yes
  file:
    path: "{{ freefeed_log_dir }}"
    state: directory

- name: Logrotate config for server logs
  become: yes
  template: src=logrotate.j2 dest="/etc/logrotate.d/freefeed-server-{{ freefeed_env }}"

- name: Start server containers
  become: yes
  docker_container:
    name: "freefeed-server-{{ freefeed_env }}-{{ ansible_loop.index }}"
    image: "ghcr.io/freefeed/freefeed-server:{{ freefeed_server_version }}"
    command: "yarn start"
    init: yes
    published_ports:
      - "{{ item }}:3000"
    volumes:
      - "{{ freefeed_config_dir }}/local-{{ freefeed_env }}.json:/server/config/local-{{ freefeed_env }}.json:ro"
      - "{{ freefeed_config_dir }}/banlist.txt:/etc/freefeed/banlist.txt:ro"
      - "{{ freefeed_config_dir }}/mailchecker.txt:/etc/freefeed/mailchecker.txt:ro"
      - "{{ freefeed_log_dir }}:/server/log"
    env:
      NODE_ENV: production
      MONITOR_PREFIX: "{{ monitor_prefix }}"
      DATADOG_HOST: '172.18.0.1'
      DATADOG_PORT: '8125'
      NODE_CONFIG_ENV: "{{ freefeed_env }}"
      FRFS_PORT: '3000'
      DEBUG: 'freefeed:user-gone,freefeed:jobs:*,-freefeed:jobs:verbose'
    networks:
      - name: freefeed
    purge_networks: yes
    healthcheck:
      test: ["CMD", "curl", "-s", "--fail", "http://localhost:3000/v2/server-info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    state: started
    restart_policy: on-failure
    recreate: "{{ local_json.changed }}"
    pull: yes
  loop: "{{ range(freefeed_base_port, freefeed_base_port+freefeed_server_instances, 1) | list }}"
  loop_control:
    pause: 5
    extended: yes

- name: "Wait for FreeFeed server to come up"
  uri:
    url: "http://localhost:{{ item }}/v2/server-info"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 5
  delay: 2
  loop: "{{ range(freefeed_base_port, freefeed_base_port+freefeed_server_instances, 1) | list }}"
  check_mode: no
  tags:
    - server-status

- include: jobs.yml
  when: freefeed_jobs_enabled
  tags:
    - freefeed-maintenance
