---

www_user: www-data
www_group: www-data

react_client_dir: /var/www/freefeed-react-client
react_client_repo: https://github.com/freefeed/freefeed-react-client.git
react_client_branch: stable
react_client_hostname: "{{ inventory_hostname }}"

