- name: Install docker pgp key
  become: yes
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg

- name: Add docker apt repository
  become: yes
  apt_repository: 
    repo: "deb https://download.docker.com/linux/debian {{ ansible_facts['distribution_release'] }} stable" 
    state: present 
    filename: docker
    update_cache: yes

- name: Install docker
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
