---

- hosts: all:!localhost
  become: yes
  tasks:
    - name: Create a group
      group:
        name: admins
        state: present

    - name: Create users
      user:
        name: "{{ item }}"
        groups: admins
        append: yes
        state: present
        shell: /bin/bash
      with_items: "{{ admins }}"

    - name: Init authorized_keys for users
      authorized_key:
        user: "{{ item }}"
        key: "{{ admins[item] }}"
        state: present
      with_items: "{{ admins }}"

    - name: Add users group in sudoers
      lineinfile:
        dest: '/etc/sudoers.d/admins'
        line: "%admins ALL=(ALL) NOPASSWD:ALL"
        state: present
        create: yes
        mode: 0440
        validate: '/usr/sbin/visudo -cf %s'
