- hosts: all
  become: yes
  vars:
    deploy_log_dir: /var/log/deploy
    deploy_files_location: /opt
  tasks:
    - name: Clone pepyatka-server
      git:
        repo: "{{ pepyatka_server_repo }}"
        dest: "{{ deploy_files_location }}/pepyatka-server"
        version: "{{ pepyatka_server_branch }}"
        force: yes
        depth: 50

    - name: Clone react-client
      git:
        repo: "{{ react_client_repo }}"
        dest: "{{ deploy_files_location }}/react-client"
        version: "{{ react_client_branch }}"
        force: yes
        depth: 50

    - name: Clone vanilla
      git:
        repo: "{{ vanilla_repo }}"
        dest: /opt/vanilla
        version: "{{ vanilla_branch }}"
        force: yes
        depth: 50
      when: vanilla_enabled

    - name: Deploy check-deploy script
      template: src=check-deploy.j2 dest=/opt/check-deploy mode=0700

    - name: Create directory for check-deploy logs
      file: path="{{ deploy_log_dir }}" state=directory

    - name: Setup logrotate for check-deploy logs
      template: src=check-deploy.logrotate.j2 dest=/etc/logrotate.d/check-deploy

    - name: Force first time deploy
      command: /opt/check-deploy --force

    - name: Setup cron job for check-deploy
      cron:
        name="Deploy freefeed"
        cron_file=check-deploy
        job="{{ deploy_files_location }}/check-deploy"
        user=root
        minute="*/5"
        state=present

