---

- hosts: all:!localhost
  become: yes
  roles:
    - security
    - swap
  tasks:
    - name: Install apt-transport-https
      apt: name=apt-transport-https state=present force=yes

    - name: Install required packages
      apt: name="{{ item }}" state=present update_cache=yes force=yes
      with_items:
        - build-essential
        - libssl-dev
        - libffi-dev
        - python-dev
        - git
        - sudo
        - mosh
        - tmux
        - silversearcher-ag
        - ntp
        - jq
        - vim
        - dbus

    - name: Ensure setuptools are not installed
      apt: name=setuptools state=absent

    - name: Fetch get-pip.py
      get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/opt/get-pip.py

    - name: Run get-pip.py
      command: python /opt/get-pip.py

    - name: Install required python modules
      pip: name="{{ item }}" state=latest
      with_items:
        - httplib2
        - markupsafe
        - prettytable

    - name: Install ansible
      pip: name=ansible version=2.1
