---

- pre_tasks:
  hosts: all
  connection: local
  gather_facts: False
  become: False
  tasks:
    - name: Delete saved changelogs
      file: path="playbooks/{{ item }}" state=absent
      with_items:
        - pepyatka-server-changelog
        - vanilla-changelog
        - react-client-changelog
      when: slack_token is defined
      tags:
        - changelog

- include: redis.yml
- include: postgres.yml
- include: pepyatka.yml
- include: pepyatka-frontend.yml

- post_tasks:
  hosts: all
  connection: local
  gather_facts: False
  become: False
  tasks:
    - name: Send pepyatka-server changelog to Slack
      local_action:
        module: slack
        token: "{{ slack_token }}"
        msg: "pepyatka-server <{{ pepyatka_server_repo | replace('.git', '')}}/compare/{{ lookup('file', item) }}|changelog>"
      with_fileglob:
        - pepyatka-server-changelog/*
      when: slack_token is defined
      tags:
        - changelog

    - name: Send react-client changelog to Slack
      local_action:
        module: slack
        token: "{{ slack_token }}"
        msg: "react-client <{{ react_client_repo | replace('.git', '')}}/compare/{{ lookup('file', item) }}|changelog>"
      with_fileglob:
        - react-client-changelog/*
      when: slack_token is defined
      tags:
        - changelog

    - name: Send vanilla changelog to Slack
      local_action:
        module: slack
        token: "{{ slack_token }}"
        msg: "vanilla <{{ vanilla_repo | replace('.git', '')}}/compare/{{ lookup('file', item) }}|changelog>"
      with_fileglob:
        - vanilla-changelog/*
      when: slack_token is defined and vanilla_enabled
      tags:
        - changelog

